### ISSUE TITLE
bind() updates property, but does not create a ChangeEvent

### ISSUE THREAD

**Issue by marrelUnderscore** [HanSolo/properties#1]
Thanks for the library, I used it quite a few times by now :)
However, I noticed something that might be a bug, but I'm not quite sure.

When binding a property B to a property A, the value of property B will be updated, but no ChangeEvent will be created (see example below). Is this intended?

### Example:
```
import eu.hansolo.properties.IntegerProperty;
public class PropDemo {
    public static void main(String[] args) {
        IntegerProperty propertyA = new IntegerProperty(99);
        IntegerProperty propertyB = new IntegerProperty(0);

        propertyB.addListener(changeEvent -> System.out.println("B changed to: " + propertyB.get()));

        propertyB.set(15); //Value of B changes to 15, Event is created

        propertyB.bind(propertyA); //Value of B changes to 99, but NO event will be created

        System.out.println("Final Value B: " + propertyB.get());
    }
}
```
### Output:
```
B changed to: 15
Final Value B: 99
```

**Comment by HanSolo** [comment]
To be honest, the properties lib was not updated for some time because I moved everything into one library called toolbox which you can find [here](https://github.com/HanSolo/toolbox)
It contains the properties, events and other useful things, you might want to use the toolbox instead because it is up to date.

**Comment by marrelUnderscore** [comment]
Oh, didn't notice that one. I'm definitly gonna keep it in mind for my other projects!
I'm unfortunately stuck on Java11 for the current project, so I cannot use the more recent builds. Since this version has so far worked out great for what I need, I think I'm gonna go with Overriding the bind() method to also fire a ChangeEvent in case the bound to property has a diffferent value.
But thank you very much! ^_^
